

#define DECLARE_DYNAMIC	    DECLARE_CLASS
#define DECLARE_DYNCREATE	DECLARE_DYNAMIC_CLASS
#define IMPLEMENT_DYNAMIC	IMPLEMENT_CLASS
#define IMPLEMENT_DYNCREATE	IMPLEMENT_DYNAMIC_CLASS
#define RUNTIME_CLASS       CLASSINFO
#define ASSERT  wxASSERT

#define ID_FILE_OPEN	wxID_OPEN
#define ID_FILE_CLOSE	wxID_CLOSE
#define ID_FILE_NEW	wxID_NEW
#define ID_FILE_SAVE	wxID_SAVE
#define ID_FILE_SAVE_AS	wxID_SAVEAS
#define ID_EDIT_CUT	wxID_CUT
#define ID_EDIT_COPY	wxID_COPY
#define ID_EDIT_PASTE	wxID_PASTE
#define ID_APP_EXIT	wxID_EXIT
#define ID_EDIT_UNDO	wxID_UNDO
#define ID_EDIT_REDO	wxID_REDO
#define ID_HELP_INDEX	wxID_HELP
#define ID_FILE_PRINT	wxID_PRINT
#define ID_FILE_PRINT_SETUP	wxID_PRINT_SETUP
#define ID_FILE_PRINT_PREVIEW	wxID_PREVIEW


